### PR TITLE
Changed get_all_apps.sh to extract newer firmware files for Mi Band 2

### PR DESCRIPTION
**Pull request by danielrheinbay**
For text and special icon notifications you need to have firmware version >=1.0.1.28 and the corresponding font files (Mili_pro.ft and Mili_pro.ft.en) installed [1]. Previously, the font files would not be get extracted because of their extensions not matching our filter (*.fw). Changed that filter to match aforementioned font files, too.
[1] https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information

### CODE REVIEW

**Comment by flycodepl** [comment]
Hi @danielrheinbay, thanks you for your working.

This fix is very useful, but unfortunately doesn't work with some apk (i.e. 2.2.8 and olders). In this apks doesn't exist *.ft or *.ft.en file. Script is stopped, because is used 'set -e' for detecting errors.
I think that the simplest method to fix it is use '-f' in cp command, but this option is ignored when is used '-n' option... :(
Have you some ideas?

**Comment by danielrheinbay** [comment]
Rsync would probably do the job. Would that be OK for you, or do you think it's too heavy?

**Comment by danielrheinbay** [comment]
I have implemented my suggestion and switched from cp to rsync. It works on my machine, but your mileage may vary. Please test it, and let me know if we're good to go :)

**Comment by flycodepl** [comment]
rsync is good idea. But you don't specified source/destination (specified only one path). I think that should be like this:
`rsync -a --include="*/*" --include="*.ft" --include="*.ft.en" --include="*.fw" --exclude="*"  ${UNZIP_APK_DIR}/assets/ $DIR_FOR_FW`

What you thing?

**Comment by danielrheinbay** [comment]
I think we're pretty close :) How about this one:
`rsync -a --include '*.fw' --include '*.ft' --include '*.ft.en' --exclude '*' ${UNZIP_APK_DIR}/assets/ $DIR_FOR_FW`
(see my latest commit)

**Comment by flycodepl** [comment]
Looks great - thank you ;)

**Pull request merged**
